http.host: 0.0.0.0

# Allow site plugin access
http.cors.enabled: true
http.cors.allow-origin: /https?:\/\/.*(:[0-9]+)?/

# Prevent discovery error on startup
discovery.type: single-node

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
